---
title: "01. workflow"
output: word_document
date: "`r Sys.Date()`"
---

Exploratory analysis

```{r}
library(tidyverse)
library(ggplot2)
library(readxl)
library(widyr)
library(janitor)
library(factoextra)
library(FactoMineR)
library(rgl)
library(viridis)
library(cluster)
library(PerformanceAnalytics)
library(cluster)
library(ggord)
library(MASS)
theme_set(theme_light())
set.seed(2024)

Cucuteni_pXRF <- read_excel("Cucuteni_pXRF.xlsx", sheet = "toate fara 15 RSD>10")
Cucuteni_pXRF <- as_tibble(Cucuteni_pXRF) |> 
  mutate_if(is.character, as.factor) |> 
  mutate_if(is.double, as.numeric)

df <- Cucuteni_pXRF |> 
as_tibble()
```

Remove P from analysis per Hunt 2015

```{r}
df <- df |> dplyr::select(!c(P_avg))  

pca_df <- PCA(df[, 3:13], scale.unit = T)

summary(pca_df)

library(psych)
outlier(df[,3:13])

df_selection <- df[-c(1, 7, 15:17),]

##Variație pe dimensiuni---

eigen_values_selection <- pca_df_selection$eig |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  clean_names() |> 
  arrange(desc(percentage_of_variance)) |> 
  as_tibble()

eigen_values_selection |> 
  top_n(4, percentage_of_variance) |> 
  ggplot(aes(rowname, percentage_of_variance)) +
  geom_col()

##Corelații variabile---
  
cors_var_selection <- pca_df_selection$var$cor |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  mutate_if(is.character, as.factor) |> 
  as_tibble()

cors_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.1)) |> 
  ggplot(aes(Dim.1, rowname)) +
  geom_col()

cors_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.2)) |> 
  ggplot(aes(Dim.2, rowname)) +
  geom_col()

cors_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.3)) |> 
  ggplot(aes(Dim.3, rowname)) +
  geom_col()

cors_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.4)) |> 
  ggplot(aes(Dim.4, rowname)) +
  geom_col()

##Contribuții variabile---

contrib_var_selection <- pca_df_selection$var$contrib |> 
  as.data.frame() |> 
  mutate_if(is.character, as.factor) |> 
  rownames_to_column() |> 
  as_tibble() 


contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.1, .desc = T)) |> 
  ggplot(aes(rowname, Dim.1)) +
  geom_col() 

contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.2, .desc = T)) |> 
  ggplot(aes(rowname, Dim.2)) +
  geom_col()


contrib_var_selection |> 
  mutate(rowname = fct_reorder(rowname, Dim.3, .desc = T)) |> 
  ggplot(aes(rowname, Dim.3)) +
  geom_col()



##Contribuții indivizi

contrib_ind_selection <- 
  pca_df_selection$ind |> 
  as.data.frame() |> 
  mutate_if(is.character, as.factor) |> 
  rownames_to_column() |> 
  as.tibble()

contrib_ind_selection |> 
  mutate(rowname = fct_reorder(rowname, coord.Dim.1, .desc = T)) |> 
  ggplot(aes(coord.Dim.1, rowname, fill = df_selection$clusters)) +
  geom_col() +
  scale_fill_viridis_d()

contrib_ind_selection |> 
  mutate(rowname = fct_reorder(rowname, coord.Dim.2, .desc = T)) |> 
  ggplot(aes(coord.Dim.2, rowname, fill = df_selection$clusters)) +
  geom_col() +
  scale_fill_viridis_d()


contrib_ind_selection |> 
  mutate(rowname = fct_reorder(rowname, coord.Dim.3, .desc = T)) |> 
  ggplot(aes(coord.Dim.3, rowname, fill = df_selection$clusters)) +
  geom_col() +
  scale_fill_viridis_d()

```

Clusters without outliers

```{r}
gradient_col <-  list(low = "black", mid = "white",high = "red")


df_centr_selection <- df_selection |> 
 as.data.frame(scale(df_selection[,3:13], scale = T, center = T)) |> 
  as_tibble()


cluster_tendency_df_centr_selection <- get_clust_tendency(df_centr_selection[,3:13], 
                                                          n = 13, 
                                                          gradient = gradient_col)      
cluster_tendency_df_centr_selection #0.68


cluster_tendency_pca <- get_clust_tendency(pca_df_selection$ind$coord[,1:5], 
                                                          n = 13, 
                                                          gradient = gradient_col)      
cluster_tendency_pca #0.66

m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")
ac <- function(x) {
agnes(df_centr_selection, method = x)$ac
}
linkages_optimum <- sapply(m, ac)

fviz_nbclust(df_centr_selection, FUN = hcut, method = "wss")
fviz_nbclust(df_centr_selection, FUN = hcut, method = "silhouette")



clust_df_centr_selection_tests <- eclust(df_centr_selection[,3:13],
                               FUNcluster = "diana",
                               k = 2,
                               hc_metric = "spearman",
                               hc_method = "ward.D2"
                               )

fviz_dend(clust_df_centr_selection_tests)
fviz_silhouette(clust_df_centr_selection_tests) 
fviz_cluster(clust_df_centr_selection_tests, repel = T)

export_clus <- clust_df_centr_selection_tests$cluster
df_selection$clusters <- as.factor(export_clus)
```

Clusters visualisation

```{r}
pca_df_selection <- PCA(df_selection[ ,3:13],
                        scale.unit = T)
graf_pca_ind_clust <- fviz_pca_biplot(pca_df_selection,
                                      axes = c(1,2),
                                      addEllipses = F, 
                                      ellipse.level = 0.65,
                                     col.ind = df_selection$clusters,
                                     #geom.ind = "point",
                                     col.var = "black",
                                     repel = TRUE,
                                     title = "Overlay of clustering results over PCA",
                                     legend.title = "Clusters")
graf_pca_ind_clust


scores_selection = as.data.frame(pca_df_selection$ind)
```


lda to confirm clustering

```{r}
df_confirmation <-  
  df_selection |> 
  dplyr::select(!c(TIP, SAMPLE))

verification_lda <- lda(df_confirmation$clusters~., df_confirmation, CV = F)
verification_lda

lda_df <- data.frame(
  clusters = df_confirmation[, "clusters"],
  lda = predict(verification_lda)$x
)
lda_df

predict_lda <- predict(verification_lda)

predict_df_lda <- 
  as_tibble(predict_lda$x)

verification_lda_cross_valid <- lda(df_confirmation$clusters~., df_confirmation, CV = T)

missclasification_lda_cross <- table(df_confirmation$clusters, verification_lda_cross_valid$class)
sum(diag(missclasification_lda_cross))/sum(missclasification_lda_cross) * 100

plot(verification_lda)
```

Clusters with outliers

```{r}
df_centr <- df |> 
 as.data.frame(scale(df[,3:13], scale = T, center = T)) |> 
  as_tibble()


cluster_tendency_df_centr <- get_clust_tendency(df_centr[,3:13], 
                                                          n = 11, 
                                                          gradient = gradient_col)      
cluster_tendency_df_centr #0.68


cluster_tendency_pca <- get_clust_tendency(pca_df_selection$ind$coord[,1:5], 
                                                          n = 13, 
                                                          gradient = gradient_col)      
cluster_tendency_pca #0.66

m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")
ac <- function(x) {
agnes(df_centr, method = x)$ac
}
linkages_optimum <- sapply(m, ac)

fviz_nbclust(df_centr, FUN = hcut, method = "wss")
fviz_nbclust(df_centr, FUN = hcut, method = "silhouette")



clust_df_centr <- eclust(df_centr[,3:13],
                               FUNcluster = "diana",
                               k = 2,
                               hc_metric = "spearman",
                               hc_method = "ward.D2"
                               )

fviz_dend(clust_df_centr)
fviz_silhouette(clust_df_centr) 
fviz_cluster(clust_df_centr, repel = T)

export_clus <- clust_df_centr$cluster
df$clusters <- as.factor(export_clus)
```

Clusters visualisation

```{r}
pca_df <- PCA(df[ ,3:13],
                        scale.unit = T)
fviz_pca_biplot(pca_df_selection,
                                      axes = c(1,2),
                                      addEllipses = F, 
                                      ellipse.level = 0.65,
                                     col.ind = df_selection$clusters,
                                     #geom.ind = "point",
                                     col.var = "black",
                                     repel = TRUE,
                                     title = "Overlay of clustering results over PCA",
                                     legend.title = "Clusters")
graf_pca_ind_clust


scores_selection = as.data.frame(pca_df_selection$ind)
```


lda to confirm clustering

```{r}
df_confirmation <-  
  df_selection |> 
  dplyr::select(!c(TIP, SAMPLE))

verification_lda <- lda(df_confirmation$clusters~., df_confirmation, CV = F)
verification_lda

lda_df <- data.frame(
  clusters = df_confirmation[, "clusters"],
  lda = predict(verification_lda)$x
)
lda_df

predict_lda <- predict(verification_lda)

predict_df_lda <- 
  as_tibble(predict_lda$x)

verification_lda_cross_valid <- lda(df_confirmation$clusters~., df_confirmation, CV = T)

missclasification_lda_cross <- table(df_confirmation$clusters, verification_lda_cross_valid$class)
sum(diag(missclasification_lda_cross))/sum(missclasification_lda_cross) * 100

plot(verification_lda)
```